language: c

dist: trusty
sudo: true

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get -qq update

install:
  - sudo apt-get -qq install libssh-dev git-buildpackage dh-apparmor devscripts debhelper

script:
  - make
  - gbp buildpackage --git-verbose --git-notify=off --git-verbose --git-ignore-branch --git-notify=off --git-force-create -i -us -uc -S -sa
  - gbp buildpackage --git-verbose --git-notify=off --git-verbose --git-ignore-branch --git-notify=off --git-force-create -i -us -uc -b
