name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: sudo apt-get -qq update && sudo apt-get install -y libssh-dev
      - name: make
        run: make
